Console.WriteLine("The shopkeeper seemed quite stressed about his variable display, so you decide to help him get it a bit organized.");
byte byteVar = 255;
sbyte sbyteVar = 127;
short shortVar = 20_125;
ushort ushortVar = 62_389;
int intVar = 1_387_381_478;
uint uintVar = 4_017_110_382;
long longVar = 8_347_329_588_121_383_901;
ulong ulongVar = 18_382_328_102_434_109_583;
double doubleVar = 3123094711709180937;
float floatVar = 8.210324f;
decimal decimalVar = 3.87e-9m;
var varVar = "I'm a var! I can be whatever I want to be!";
string stringVar = "I'm a string, and I'm more specific than var is.";
bool boolVar = true;
Console.WriteLine($"byte: {byteVar}\nsbyte: {sbyteVar}");
Console.WriteLine($"short: {shortVar}\nushort:{ushortVar}");
Console.WriteLine($"int: {intVar}\nuint: {uintVar}");
Console.WriteLine($"long: {longVar}\nulong: {ulongVar}");
Console.WriteLine($"double: {doubleVar}\nfloat: {floatVar}\ndecimal: {decimalVar}");
Console.WriteLine($"{Environment.NewLine}Since the shopkeeper asked nicely, you show him how to update the variables.");
Console.WriteLine($"var: {varVar}\nstring: {stringVar}\nbool: {boolVar}");
byteVar -= 234;
sbyteVar *= -1;
shortVar /= 2;
ushortVar -= 8_257;
intVar -= 432_432_432;
uintVar /=2 + 324_987;
longVar /= 2;
ulongVar /= 4;
doubleVar -= 432098432020;
floatVar /= 3.89f;
decimalVar /= 1000;
varVar = "WOO HOO FREEDOM!";
stringVar = "I can be used more or less interchangeably with var but I'm more specific with my instructions";
boolVar = false;
Console.WriteLine("You see the following variables have been updated:");
Console.WriteLine($"byte: {byteVar}\nsbyte: {sbyteVar}");
Console.WriteLine($"short: {shortVar}\nushort:{ushortVar}");
Console.WriteLine($"int: {intVar}\nuint: {uintVar}");
Console.WriteLine($"long: {longVar}\nulong: {ulongVar}");
Console.WriteLine($"double: {doubleVar}\nfloat: {floatVar}\ndecimal: {decimalVar}");
Console.WriteLine($"var: {varVar}\nstring: {stringVar}\nbool: {boolVar}");